apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  labels: 
    package: data
  annotations:
    app.ibm.com/is-local-deployable: "false"
    app.ibm.com/deployable-version: "1.2.0"
  name: sample-deploy-120
  generateName: sample-deploy-
  namespace: dev-qa
spec:
  template:
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        app: nginx
      name: sample-deployment
      namespace: default
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - image: nginx:1.7.9
            name: nginx
            ports:
            - containerPort: 80
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  labels:
    package: data
  annotations:
    app.ibm.com/is-local-deployable: "false"
    app.ibm.com/deployable-version: "1.0.0"
  name: sample-configmap-100
  generateName: sample-configmap-
  namespace: dev-qa
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: sample-configmap
      namespace: default
    data:
      purpose: for demo
