apiVersion: v1
kind: ConfigMap
metadata:
  name: 1demo-nginx-configmap
  namespace: default
data:
  nginx.conf: |-
    events {
      worker_connections  1024;
    }

    http {
      server {
          listen 80;

          location = / {
            add_header Content-Type text/html;
            return 200 "<H1>hello world <p><p> ${hostname}</H1>";
          }
      }
      }

