apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibm-bai-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: /data/persistentvolumes/bai/ibm-bai-pv
    server: 169.62.194.212
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: baiproject
    name: ibm-bai-pvc

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ibm-bai-pvc
  namespace: baiproject
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibm-bai-ek-pv-0
  namespace: baiproject
spec:
  storageClassName: "bai-ek-data"
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /data/persistentvolumes/bai/ibm-bai-ek-pv-0
    server: 169.62.194.212
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibm-bai-ek-pv-1
  namespace: baiproject
spec:
  storageClassName: "bai-ek-data"
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /data/persistentvolumes/bai/ibm-bai-ek-pv-1
    server: 169.62.194.212
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibm-bai-ek-pv-2
  namespace: baiproject
spec:
  storageClassName: "bai-ek-data"
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /data/persistentvolumes/bai/ibm-bai-ek-pv-2
    server: 169.62.194.212
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibm-bai-ek-pv-3
  namespace: baiproject
spec:
  storageClassName: "bai-ek-data"
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    path: /data/persistentvolumes/bai/ibm-bai-ek-pv-3
    server: 169.62.194.212
  persistentVolumeReclaimPolicy: Recycle

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibm-bai-ek-snapshots-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Gi
  nfs:
    path: /data/persistentvolumes/bai/es-snapshots-pv
    server: 169.62.194.212
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: baiproject
    name: ibm-bai-ek-snapshots-pvc

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ibm-bai-ek-snapshots-pvc
  namespace: baiproject
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
      