default:
  title: IBM Cloud Paks Playbook
  icon: book
  hidden: true

mcm:
  title: Cloud Pak for Multicloud Management
  icon: wrench

automation:
  title: Cloud Pak for Automation
  icon: rocket

integration:
  title: Cloud Pak for Integration
  icon: sitemap

data:
  title: Cloud Pak for Data
  icon: pencil
  
apps:
  title: Cloud Pak for Applications
  icon: code

ocp:
  title: OpenShift and common services
  icon: book


multipak:
  title: Multiple Cloud Paks
  icon: book