apiVersion: v1
kind: Namespace
metadata:
  name: minio
spec:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-multicluster
  namespace: minio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-multicluster
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-multicluster
subjects:
- kind: ServiceAccount
  name: ibm-multicluster
  namespace: minio
roleRef:
  kind: ClusterRole
  name: ibm-multicluster
  apiGroup: rbac.authorization.k8s.io

