apiVersion: v1
kind: Namespace
metadata:
  name: demo-workspace
spec:
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: sample-demo
  name: sample
  namespace: demo-workspace
spec:
  placement:
    placementRef: 
      name: sample
      kind: PlacementRule
      group: app.ibm.com
  channel: dev-qa/dev-qa
  packageFilter:
    version: ">=1.x"
    labelSelector:
      matchLabels:
        package: data
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: sample
  namespace: demo-workspace
spec:
  clusterReplicas: 0
  clusterLabels: {}
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sample
  namespace: demo-workspace
spec:
  selector:
    matchLabels:
      purpose: sample-demo
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
