apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ template "single.fullname" . }}
  labels:
    app: {{ template "single.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: {{ template "single.fullname" . }}
spec:
  selector:
{{ toYaml .Values.app.selector | indent 4 }}
  componentKinds:
{{ toYaml .Values.app.componentKinds | indent 4 }}
