apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: deployables.app.ibm.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.template.kind
    description: Kind of the template
    name: template-kind
    type: string
  - JSONPath: .spec.template.apiVersion
    description: api version of the template
    name: template-apiversion
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: age
    type: date
  - JSONPath: .status.phase
    name: status
    type: string
  group: app.ibm.com
  names:
    kind: Deployable
    plural: deployables
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            channels:
              items:
                type: string
              type: array
            dependencies:
              items:
                properties:
                  annotations:
                    type: object
                  labels:
                    type: object
                type: object
              type: array
            overrides:
              items:
                properties:
                  clusterName:
                    type: string
                  clusterOverrides:
                    items:
                      type: object
                    minItems: 1
                    type: array
                required:
                - clusterName
                - clusterOverrides
                type: object
              type: array
            placement:
              properties:
                clusterSelector:
                  type: object
                clusters:
                  items:
                    properties:
                      name:
                        type: string
                    type: object
                  type: array
                placementRef:
                  type: object
              type: object
            template:
              type: object
          required:
          - template
          type: object
        status:
          properties:
            targetClusters:
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []