---
# Create a Namespace to hold the Channel "secrets"
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
# Create a Namespace to hold the Channel "secrets"
apiVersion: v1
kind: Namespace
metadata:
  name: cloudpak4integration
---
# Create a Channel that declares resources that can be deployed
# Channel can be a Namespace, Object Store Bucket, or Helm Repo
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: secrets
  namespace: vault
spec:
  type: Namespace
  pathname: vault
---
#Secret mq-for-me
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    secret: mqadvanced-server-secret
  name: mq-secret
  namespace: vault
spec:
  template:
    apiVersion: v1
    kind: Secret
    metadata:
      name: mq-secret
    type: Opaque
    data:
      adminPassword: bXEtZm9yLW1l
      appPassword: bXEtZm9yLW1l
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: mq-advanced-server
  name: mq-advanced-server-secret
  namespace: cloudpak4integration
spec:
  channel: vault/secrets
  packageFilter:
    labelSelector:
      matchLabels:
        secret: mqadvanced-server-secret
  placement:
    multicluster:
      enabled: true
      labelSelector:
        matchLabels:
          environment: Dev
