# Create a Namespace to hold the Channel "dev"
apiVersion: v1
kind: Namespace
metadata:
  name: ibmcom
spec:
---
# Create a Channel that declares resources that can be deployed
# Channel can be a Namespace, Object Store Bucket, or Helm Repo
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: ibm-stable-charts
  namespace: ibmcom
spec:
    type: HelmRepo
    pathname: https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
    configMap:
      insecureSkipVerify: true
#---
# Deployables provide a reference to an Object that can be
# deployed (either embedded or referenced via Helm Chart)
#apiVersion: app.ibm.com/v1alpha1
#kind: Deployable
#metadata:
#  annotations:
#    app.ibm.com/is-local-deployable: "false"
#  name: mq-dev-test
#  namespace: quality-assurance
#spec:
#  template:
#    apiVersion: apps/v1
#    kind: Deployment
#    metadata:
#      name: mq-dev
#      labels:
#        app: mq-dev
#    spec:
#      apiVersion: helm.bitnami.com/v1
#      kind: HelmRelease
#      metadata:
#        name: mydb
#      spec:
#        # 'stable' repo
#        repoUrl:  https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
#        chartName: ibm-mqadvanced-server-dev
#        version: 4.1.0
