---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: mq-advanced-server
  name: mq-advanced-server
  namespace: cloudpak4integration
  annotations:
    tillerVersion: 2.9.1
spec:
  channel: ibmcom/ibm-stable-charts
  source: https://raw.githubusercontent.com/IBM/charts/master/repo/stable/
  name: ibm-mqadvanced-server-dev
  packageFilter:
    version: "4.1.1"
  placement:
    multicluster:
      enabled: true
      labelSelector:
        matchLabels:
          environment: Dev
  packageOverrides:
  - packageName: ibm-mqadvanced-server-dev
    packageOverrides:
    - path: spec.values
      value: "persistence:\n  enabled: false\n  useDynamicProvisioning: false\nlicense: accept\nqueueManager:\n  dev:\n    secret:\n      adminPasswordKey: adminPassword\n      name: mq-secret\n"
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mq-advanced-server
  namespace: cloudpak4integration
spec:
  selector:
    matchExpressions:
    - key: purpose
      operator: In
      values:
      - mq-advanced-server
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
