apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: {{ template "qodapp.fullname" . }}-db
  labels:
    name: {{ template "qodapp.fullname" . }}-db
    app: {{ template "qodapp.fullname" . }}
    servicekind: ApplicationService
spec:
  deployer:
    kind: helm
    helm:
      chartURL: https://gitlab.169.60.97.238.nip.io/quote-of-the-day/qod-db/raw/master/deployment/qod-db-1.0.0.tgz 
      namespace: {{ .Values.appInClusterNamespace }}
