apiVersion: v1
kind: Namespace
metadata:
  name: demo-workspace
spec:
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: sample-demo
  name: frontend
  namespace: demo-workspace
spec:
  placement:
    placementRef: 
      name: frontend
      kind: PlacementRule
      group: app.ibm.com
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: default
  channel: dev-qa/dev-qa
  packageFilter:
    version: ">=1.x"
    labelSelector:
      matchLabels:
        package: data
        component: frontend
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: frontend
  namespace: demo-workspace
spec:
  clusterReplicas: 0
  clusterLabels: {}
  clusterConditions:
  - type: OK
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    purpose: sample-demo
  name: backend
  namespace: demo-workspace
spec:
  placement:
    placementRef: 
      name: backend
      kind: PlacementRule
      group: app.ibm.com
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: default
  channel: dev-qa/dev-qa
  packageFilter:
    version: ">=1.x"
    labelSelector:
      matchLabels:
        package: data
        component: backend
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: backend
  namespace: demo-workspace
spec:
  clusterReplicas: 0
  clusterLabels: {}
  clusterConditions:
  - type: OK
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sample
  namespace: demo-workspace
spec:
  selector:
    matchLabels:
      purpose: sample-demo
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
