apiVersion: mcm.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: {{ template "crd-deployable.fullname" . }}-consumer
  labels:
    name: {{ template "crd-deployable.fullname" . }}-consumer
    app: {{ template "crd-deployable.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  deployer:
    kind: Deployment
    kube:
      namespace: {{ .Values.appInClusterNamespace }}
      template:
        metadata:
          name: {{ template "crd-deployable.fullname" . }}-consumer
        spec:
          selector:
            matchLabels:
              app: {{ template "crd-deployable.name" . }}
              release: {{ .Release.Name }}
              component: consumer
          replicas: 1
          template:
            metadata:
              labels:
                app: {{ template "crd-deployable.name" . }}
                release: {{ .Release.Name }}
                component: consumer
            spec:
              containers:
                - name: consumer
                  image: "k3integrations/kubectl"
                  imagePullPolicy: IfNotPresent
                  command: [ "/bin/sh" ]
                  args: [ "-c", "kubectl get {{ .Values.crd.spec.names.kind }} && echo Finished && sleep 1000 " ]

