apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    kubernetes.io/description: "This policy is required to allow ibm-dba-ek pods running Elasticsearch to use privileged containe
rs."
  name: bai-prod-release-bai-psp
spec:
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bai-prod-release-bai-role
  namespace: baiproject
rules:
- apiGroups:
  - extensions
  resourceNames:
  - bai-prod-release-bai-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bai-prod-release-bai-psp-sa  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bai-prod-release-bai-rolebinding
  namespace: baiproject
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bai-prod-release-bai-role
subjects:
- kind: ServiceAccount
  name: bai-prod-release-bai-psp-sa
  namespace: baiproject    	
