# Licensed Materials - Property of IBM
# IBM Cloud private
# @ Copyright IBM Corp. 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
image_repo: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64
private_registry_enabled: true
private_registry_server: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com
docker_username: <uid>
docker_password: <key>
chart_repo:
  addons:
    url: "https://na.artifactory.swg-devops.com/artifactory/ui/artifactactions/downloadfolder?repoKey=hyc-cloud-private-edge-helm-local&path=3.2.1&archiveType=tgz&includeChecksumFiles=false"
    header: "X-JFrog-Art-Api: <key>"


# A list of OpenShift nodes that used to run ICP components
cluster_nodes:
  master:
    - 10.148.87.135
  proxy:
    - 10.148.87.135
  management:
    - 10.148.87.186

storage_class: ibmc-block-bronze
openshift:
    console:
        host: c100-e-us-east-containers-cloud-ibm-com
        port: 32653
    router:
        cluster_host: icp-console.mcmresidency1-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud
        proxy_host: icp-proxy.mcmresidency1-6550a99fb8cff23207ccecc2183787a9-0001.us-east.containers.appdomain.cloud

default_admin_password: admin
password_rules:
- '(.*)'

## You must have different ports if you deploy nginx ingress to OpenShift master node
# ingress_http_port: 80
# ingress_https_port: 443

#### enable it if you want to install MCM Hub together
single_cluster_mode: false

## You can disable following services if they are not needed
## Disabling services may impact the installation of IBM CloudPaks.
## Proceed with caution and refer to the Knowledge Center document for specific considerations.
# auth-idp
# auth-pap
# auth-pdp
# catalog-ui
# helm-api
# helm-repo
# icp-management-ingress
# metering
# metrics-server
# mgmt-repo
# monitoring
# nginx-ingress
# platform-api
# platform-ui
# oidcclient-watcher
# secret-watcher
# iam-policy-controller
# security-onboarding
# web-terminal

management_services:
  monitoring: enabled
  metering: enabled
  logging: disabled
  custom-metrics-adapter: disable
