apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: {{ template "mq.fullname" . }}
  labels:
    app: {{ template "mq.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: {{ template "mq.fullname" . }}
    servicekind: CacheService
placementRef:
  apiGroup: mcm.ibm.com
  kind: PlacementPolicy
  name: {{ template "mq.fullname" . }}
subjects:
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: {{ template "mq.fullname" . }}
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: {{ template "mq.fullname" . }}-server
  labels:
    app: {{ template "mq.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    name: {{ template "mq.fullname" . }}
    servicekind: CacheService
placementRef:
  apiGroup: mcm.ibm.com
  kind: PlacementPolicy
  name: {{ template "mq.fullname" . }}-server
subjects:
- apiGroup: mcm.ibm.com
  kind: Deployable
  name: {{ template "mq.fullname" . }}-server
