apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  namespace: default
  name: qotdapp
  labels:
    app: qotdapp
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - qotdapp
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
  - group: core
    kind: Pods
  - group: core
    kind: Service
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet

